// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $account_index from "./routes/account/index.tsx";
import * as $account_login from "./routes/account/login.tsx";
import * as $account_signup from "./routes/account/signup.tsx";
import * as $dev_Data from "./routes/dev/Data.tsx";
import * as $dev_Family from "./routes/dev/Family.tsx";
import * as $dev_Recover from "./routes/dev/Recover.tsx";
import * as $dev_RecoverMenu from "./routes/dev/RecoverMenu.tsx";
import * as $index from "./routes/index.tsx";
import * as $CreateFamily from "./islands/CreateFamily.tsx";
import * as $Editor from "./islands/Editor.tsx";
import * as $Recover from "./islands/Recover.tsx";
import * as $RecoverMenu from "./islands/RecoverMenu.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/account/index.tsx": $account_index,
    "./routes/account/login.tsx": $account_login,
    "./routes/account/signup.tsx": $account_signup,
    "./routes/dev/Data.tsx": $dev_Data,
    "./routes/dev/Family.tsx": $dev_Family,
    "./routes/dev/Recover.tsx": $dev_Recover,
    "./routes/dev/RecoverMenu.tsx": $dev_RecoverMenu,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CreateFamily.tsx": $CreateFamily,
    "./islands/Editor.tsx": $Editor,
    "./islands/Recover.tsx": $Recover,
    "./islands/RecoverMenu.tsx": $RecoverMenu,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
